### PR TITLE
Update dependencies for Node v0.12

### PR DESCRIPTION
**Pull request by MattiSG**

### CODE REVIEW

**Comment by fpagnoux** [comment]
Seems GTM, i had no problem npm installing it.

**Comment by MattiSG** [comment]
> i had no problem npm installing it.

Did you also `npm link` in `mes-aides-ui` and run the server?

**Comment by fpagnoux** [comment]
Just did it, the ludwig interface works as expected.

**Comment by MattiSG** [comment]
Published on NPM as 1.2.0.

**Pull request merged**
